### ISSUE TITLE
New Pool Request: XEX/USDC 80/20 on polygon and mainnet

### ISSUE THREAD

**Issue by farmerbrowndefi** [BalancerMaxis/maxi-balpy#3]
### Unsupported token types
- Tokens that rebase 
- Needs a wrapper
- Tokens that charge tx fees.

### What style pool do you want, delete all but one
WeightedPool

### What Chain(s)
mainnet, polygon

### What tokens would you like in the pool, and if weighted pool in what ratios **

Weighted Pool: 

XEX (80%) 0xa41A879bcFdd75983a987FD6b68fae37777e8b28 (both chains)
USDC (20%)

### What should the fees be set too
1.88%

### Are any of your tokens interest bearing?
No

### How do you get the price per share of the interest baring token(s) (For Example: 1 wstETH in ETH) 
Link to contract on block scanner and mention read function.  Or if you have already deployed [RateProviders](https://docs.balancer.fi/reference/contracts/rate-providers.html) let us know the address per token.

###  Do you want to want your pool with interest baring tokens to be a core pool? 
 If this is a weighted pool, you can decide if you balancer to take fees on the interest baring portion of the pool, causing this pool to be a Core Pool and particpate in the [BIP-19 Brib System](https://forum.balancer.fi/t/bip-19-incentivize-core-pools-l2-usage/3329).

No

### Is it OK if permission to manage the fees and a-factor are deleted to balancer governance.  This is expected for a gauge.  If not, what address should be owner of the pool 
Yes

### We will need to get in touch with you
Please ping [Tritium](https://t.me/tritium_vlk) or [Zen Dragon](https://t.me/Z_Dragon) or MikeB(https://t.me/mikeisballin) or another Maxi and reference this ticket.  JUST ONE OF US PLEASE :).  We want to make sure you are talking to right person before you send tokens.

## Now what:
Someone will get in touch with you and give a deployer address to send tokens to.  We will deposit all of the tokens provided when creating the pool.  The ratio of the tokens deposited will determine the initial price.  For this reason you need to send tokens such that depositing  them all provides a market price.  If this is a stableswap at peg, it should be equal amounts of each pool.  If this is a weighted pool, tokens should be provided such that adding them at the specified weights results in the proper market price.  Let us know if you need help with this.  A very simple example, in a 50/50 pool if 1 COIN costs .5 USDC, then you should provide something like 100 USDC and 50 COIN.  Please do not send over 500 dollars in value.

## Check list (for deployer)
-  [x] Tokens Received
-  [x] Check/Deploy rate providers
-  [ ] Pool Deployed
-  [ ] UI pull request submitted
-  [ ] Pool tokens sent back

**Comment by Tritium-VLK** [comment]
Polygon pool: https://app.balancer.fi/#/polygon/pool/0x7104ad560c1d74aabc108bc51114db121b927a9d000200000000000000000b2a
Pool tokens returned: https://polygonscan.com/tx/0xdd435cc29a4b7a4d127132007563631509a6c6d1299cdd225bd59c3772e4fa0f

**Comment by Tritium-VLK** [comment]
Mainnet Pool:
https://app.balancer.fi/#/ethereum/pool/0x0fadd10f606554fec1574f28398469d98d68d297000200000000000000000503
Transfer back pool tokens:
https://etherscan.io/tx/0xedcb09fe07749d27012574ee3f42235c97d0d326013fbfc47af3c1858875e6a9

**Comment by Tritium-VLK** [comment]
Polygon pool has wrong pool name XES instead of XEX.  Rebuilding.

**Comment by Tritium-VLK** [comment]
BALPY pr: #4

**Comment by Tritium-VLK** [comment]
PR for whitelisting of pool:
https://github.com/balancer/frontend-v2/pull/3141

**Comment by Tritium-VLK** [comment]
PR for addition to tokenlist:
https://github.com/balancer/tokenlists/pull/20
